apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nodeapp
  labels:
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nodeapp
    spec:
      containers:
      - name:  nodeapp
        image: 393336400542.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  4000