apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
    - name: nodeapp
      protocol: TCP
      port: 5000
      targetPort: 4000
      nodePort: 30090